### PR TITLE
Lock system with text indicator

### LINKED ISSUE #33: Lock system
For the company I work for, we make use of a lock system, to restrict player movement whilst using UI, or in a cutscene.

The way we found best, is a privately settable Dictionary of strings.

`Locks.AddLock("TalkingToCompanionA")`

`Locks.RemoveLock("TalkingToCompanionA")`

Input can then check locks.count/locks.length etc with a property or method, e.g.

```
if(!Locks.IsLocked)
{
    //accept input
}
```

- The strings are set by developers, and help with debugging as we can print out what's going on.

- The collection is important, as it means multiple things can manipulate the locks without unlocking things unintentionally 
- e.g. A player is on a pause menu, fast travels, then return to the pause menu without the fast travel's locks interfering with the pause menu still needing the player to be immobile after the animation.

This one is something I'd be happy to work on, but only if it's useful. :)

### PR DESCRIPTION
**Pull request by TheFunnyBrain**
To add feature/issue #33 (locks) I've implemented a system we use at my workplace.

Presently it's a simple implementation, and I've tried to keep things very minimal.

It's possible to extend this by adding multiple lock components for various things (physics update, camera controls etc), but I'd like to make sure this works as designed, and follows the principles of existing code before overdoing it.

It uses the GameAttribute system to display a brief message explaining that the user needs to press p to restore movement.

To stop the player running for eternity, I reset their movement in PlayerController.gd. This might not be best practice, and thought it was worth drawing attention to in case it's a terrible way to solve the problem! :)

		`direction = Vector3.ZERO
		character_component.add_movement_input()`

In terms of use cases, locks can be applied to practically any element of a game or character system
- Movement (implemented in this pull request) - e.g. sitting in a seat, talking to an NPC, cutscenes
- Camera control - force player to look at something, separated to allow player to look around independent of movement.
- Locking physics updates - player freeze, game pause, etc
- Game logic - anything that needs dynamic conditions to be added and removed e.g. level selection requirements, NPC dialogue options

### CODE REVIEW

**Comment by ywmaa** [comment]
## 1-  
> To stop the player running for eternity, I reset their movement in PlayerController.gd. 

currently for this system, this is the right way!
I think I should add a function in the system later for one_time_stop() / movement_reset()

## 2- maybe add another signal : 

signal Lock_Removed(lockName:String)

## 3- Using PausedAttribute.gd

in the first place I made GameAttribute for stuff like health and stamina, your use of it is quite interesting,
do you think that it is worth it to have Pause Variable as a Player Attribute ?
or having it as a variable `var is_locked : bool `  in the LockSystem.gd will be enough ?

but also having it as a GameAttribute is quite inpsiring for Template users to use GameAttribute Creatively.
so I am not sure what we should go with, what is your opinion on it ?

**Comment by TheFunnyBrain** [comment]
> ## 1-
> 
> > To stop the player running for eternity, I reset their movement in PlayerController.gd.
> 
> currently for this system, this is the right way! I think I should add a function in the system later for one_time_stop() / movement_reset()
> ## 2- maybe add another signal :
> 
> signal Lock_Removed(lockName:String)
> ## 3- Using PausedAttribute.gd
> 
> in the first place I made GameAttribute for stuff like health and stamina, your use of it is quite interesting, do you think that it is worth it to have Pause Variable as a Player Attribute ? or having it as a variable `var is_locked : bool ` in the LockSystem.gd will be enough ?
> 
> but also having it as a GameAttribute is quite inpsiring for Template users to use GameAttribute Creatively. so I am not sure what we should go with, what is your opinion on it ?

Thanks :) That's great to know :) I considered adding a function, but didn't want to go too far out of scope for a first commit! :)

# 2
Thank you, I've added the signal for removing locks in, that was an oversight on my part. :)

# 3
At work, we just use NavigationManager.IsLocked and InteractionManager.IsLocked, so I feel it could be simplified without any real headaches. :)

It could be nice to have some lock states as player attributes (e.g. to track player abilities, status effects), however it is very likely overkill, not to mention, a true pause would be a more global game-level variable.

I'll demote the UI to read is_locked, as that's plenty for just manipulating player navigation.

**Comment by TheFunnyBrain** [comment]
# 3 - Using PausedAttribute.gd
One better, I'm using signals, as they are wonderful and much easier than making a node just to enable the label object! :)

**Comment by ywmaa** [comment]
Looks good, thanks for the very nice system.
Also Thanks for fixing the Typos (References, mouse_sensitivity)

**Pull request merged**
